### ISSUE TITLE
RetinaFace: Single-stage Dense Face Localisation in the Wild

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#10]
기존의 face detection은 wild(자연 상태)일 때는 detection에 어려움이 있었는데 이를 보완하기 위해 모델이다.

RetinaFace는 extra-supervised와 self-supervised의 장점을 가져와 대상의 크기에 상관없이 픽셀 단위로 face detection한다. 
특히 아래의 5가지 측면에 기여했다.

1.  WIDER FACE 데이터셋에서 얼굴에 5개의 랜드마크를 직접 표시했고, hard face detection에 큰 개선을 했다.
2.  픽셀 단위의 3D 얼굴 모양 정보를 예측하는 self-supervised mesh decoder branch를 추가했다.
3.  WIDER FACE hard dataset에서 기존 SOTA 모델보다 AP가 1.1% 높다.
4.  IJB-C test set에서는 기존 SOTA 모델(ArcFace)보다 face verification 성능을 더 높였다.
5.  backbone networks을 가볍게 하면 싱글 코어 CPU 환경에서도 실시간으로 수행이 가능하다.

기존의 SOTA 모델들의 테크닉들을 합리적으로 동원해 만든 새로운 SOTA face detection 모델이다.

**Comment by binable43** [comment]
우와 wild 상태에서도 detection을 할 수 있는데다 SOTA 모델이라니! 너무 좋은 모델이네요 👍 잘 읽고 갑니다 :)

**Comment by ssongedev** [comment]
우와 나중에 한번 사용해보고 싶네요!! 너무 흥미로운 내용이에요! 덕분에 잘 읽었습니다! :)

**Comment by SEOJIN-Lab** [comment]
새로운 SOTA 모델이라니...! 너무 좋네요! 잘 읽었습니다:>

**Comment by chaerin314** [comment]
기존 모델보다 개선이 많이 된 face detection 모델이군요! 알아둬야겠네요ㅎㅎ
