### ISSUE TITLE
EfficientNetV2: Smaller Models and Faster Training

### ISSUE THREAD

**Issue by chaerin314** [gdscewha-3rd/Study-PaperReview#11]
- **기존 EfficientNet의 training bottlenecks**
    - **EfficientNet** : FLOPs와 parameter efficiency에 최적화된 모델, but
    (i) Training with very large image sizes is slow
    (ii) Depthwise convolutions are slow in early layers (but effective in later stage)
    (iii) Equally scaling up every stage is sub-optimal
- **Contribution of this article**
    - EfficientNetV2; training-aware NAS and scaling: speed ↑, parameter efficiency ↑
    - Improved progressive learning; image size에 맞춰 regularization: speed ↑, accuracy ↑
    - Test datasets에서 11x faster, 6.8x better parameter efficiency

- **EfficientNetV2 Architecture Design**
    - NAS search의 효율화 : EfficientNet이 backbone, 불필요한 선택지를 지우거나 이미 탐색한 것의 channel size를 재사용함으로써 search space size를 줄임)
    - Architecture : 기존 EfficientNet과의 차이
        1. 초반 layers에 MBConv, Fused-MBConv 둘 다 사용 -> (ii) 해결
        2. smaller expansion ratio를 가짐
        3. smaller 3x3 kernel size (but, more layers)
        4. 마지막 stride-1 stage 제거
    - Scaling을 다르게 함 : max inference image size 제한(480), 후반 stage에 layer 추가 -> (iii) 해결
    - Progressive Learning with adaptive regularization : 초반 epoch에서는 smaller images를 weak regularization으로 학습하고, 점차 image size를 늘리며 regularization도 강하게 적용 -> (i) 해결
        *기존에는 large model를 다룰 때 오버피팅을 막기 위해 strong regularization을 필요로 했고, 이는 accuracy drop을 일으킬 수 있었음, 또는 애초에 메모리 한계로 small batch size를 이용해야 되므로(학습속도 느려짐) image size를 줄여 사용하기도 했음

**Comment by binable43** [comment]
speed와 accuracy를 높인 모델이라니! 대단하네요 👍  덕분에 잘 읽고 갑니다 :)

**Comment by ssongedev** [comment]
적은 파라미터수로 SOTA를 달성한 EfficientNet을 더 효율적으로 만든 모델이군요!! 덕분에 잘 읽었습니다! :)

**Comment by SEOJIN-Lab** [comment]
잘 읽고 갑니다:>

**Comment by minha62** [comment]
adaptive regularization이라는 방법도 있군요! 좋은 내용 잘 읽고 갑니다:)
