### ISSUE TITLE
Speech Emotion Recognition using MFCC features and LSTM network

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#12]
### SER(Speech Emotion Recognition)을 다룬 논문
- MFCC(특징추출), LSTM Algorithm

### MFCC
**Mel-Frequency Cepstral Coefficient (MFCC)** is a popular and powerful analytical tool in the field of speech recognition. 
1) approach의 computational complexity를 줄인다 
2) feature를 추출하는데 better ability를 제공
3) find the different parameters like pitch and energy
4) reduces the frequency info. of speech signal into the small number of coefficients which is easy to compute and extract the features

### Machine Learning model - LSTM
- Long short-term memory (LSTM) is a modified version of artificial recurrent neural network(RNN) architecture.
- LSTM works better with a huge amount of data and enough training data.

### Dataset
- RAVDESS 사용
- 7356 files containing speech data  of 12 female and 12 male actors
- neutral North American accent
- calm, happy, sad, angry, fearful, surprise, disgust (7개)
- 16bit, 48 kHz
- file format : .wav

**Comment by ssongedev** [comment]
MFCC로 오디오에서 특징을 추출해서 LSTM로 분류하는 방법을 새로 알게 되었어요! 덕분에 재미있게 읽고 갑니다:)

**Comment by SEOJIN-Lab** [comment]
엄청 흥미로운 내용이네요...! 정리 감사합니다:>

**Comment by chaerin314** [comment]
요즘 LSTM을 공부하고 있었는데 실제 응용 사례를 보니 더 도움이 되네요! MFCC에 대해서도 좀 더 알아봐야겠어요ㅎㅎ 잘 읽고갑니다:)

**Comment by minha62** [comment]
다음에 프로젝트에 활용해보고 싶어지네요!! 좋은 내용 감사합니다:)
