### ISSUE TITLE
Optuna: A Next-generation Hyperparameter Optimization Framework

### ISSUE THREAD

**Issue by chaerin314** [gdscewha-3rd/Study-PaperReview#13]
hyperparameter optimization에 사용하는 자동화 툴 중 비교적 최근에 등장했고, 많이 사용되는 Optuna를 소개하는 논문이다.
다음과 같은 3가지 측면의 new design-criteria를 제안한다.
- define-by-run API : 사용자가 parameter search space를 다양하게 구성 가능
- efficient searching & pruning algorithm : cost effectiveness of optimizatoin 향상
- easy-to-setup, scalable & versatile architecture : 다양한 목적으로 프레임워크를 전개할 수 있음

**Comment by minha62** [comment]
하이퍼파라미터 최적화에 사용되는 툴을 찾아본 적은 없었는데 채린벗 덕분에 하나 알게 되었네요!
좋은 내용 감사합니다:)

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by m0oon0** [comment]
첨 들어봤는데 저도 라이브러리 사용해보고싶네요!! 잘 읽었습니다👍
