### ISSUE TITLE
Speech Emotion Recognition Using Speech Feature and Word Embedding

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#14]
### Accuracy
    - Multimodal : 75.49%
    - Speech only : 58.29%
    - Text only : 68.01%

### Contents

The current research on **pattern recognition** also shows that **the use of multimodal features increases the performance compared to single modality.**

The big data research also shows that **the use of more data will improve the performance** comparing to small data on the same algorithm.

→ 멀티모달 사용 & big data 사용은 성능을 더욱 향상시킨다

This paper reports the use of a simple method to **improve accuracy on SER by using a combination of speech and text features.**

**Comment by minha62** [comment]
멀티모달이라는 용어를 요즘 자주 봤는데 이번 기회에 찾아봐야겠어요!
single modality보단 멀티모달이 더 성능에 좋다는 특징을 배웠네요!
좋은 내용 감사합니다:)

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by m0oon0** [comment]
감정 인식 흥미로워요! 잘읽었습니다 👍

**Comment by chaerin314** [comment]
요즘 공부하는 부분이었는데 참고해야겠네요! 잘 읽었습니다:)
