### ISSUE TITLE
TabNet : Attentive Interpretable Tabular Learning

### ISSUE THREAD

**Issue by m0oon0** [gdscewha-3rd/Study-PaperReview#16]
- high-performance & interpretable deep tabular data learning architecture
- Uses sequential attention to choose which features to reason at each step

- Attentive Transformer -> feature selection : learnable mask M[i] = sparsemax(P[i−1] · hi(a[i−1]))
   P = prior scale term, denoting how much a particular feature has been used previously
   a = processed features from the preceding step
- Feature Transformer : Embed the selected features into prediction function. 
   FC layer + Batch Normalization + GLU

- Unlike tree-based algorithm, TabNet uses instance-wise feature selection. 
- Each step gets its own vote in final classification, which mimics an ensemble classification task.
- Able to figure out which features are selected by the model through feature selection masks (locally & globally)

**Comment by minha62** [comment]
그동안 정형 데이터에서는 딥러닝보다 트리 기반이 성능이 좋았는데, 정형 데이터를 위한 딥러닝 architecture를 만든거군요!
좋은 내용 감사합니다:)

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by chaerin314** [comment]
잘 읽었습니다!
