### ISSUE TITLE
GAN: Generative Adversarial Networks

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#18]
`Adversarial Learning(경쟁)`을 통해 생성 모델을 추정하는 새로운 프레임워크

<br>

generator와 discriminator 두 모델을 경쟁적으로 학습시켜 동시에 최적화

1. `generative model, G`: D가 구별하지 못하도록 훈련 데이터의 분포를 모사
2. `discriminative model, D`: 샘플 데이터가 G로부터 나온 데이터가 아닌 실제 훈련 데이터로부터 나온 데이터일 확률을 추정

➡️ G는 실제 훈련 데이터의 분포를 모사해 그와 비슷한 데이터를 생성하고, D는 실제 데이터와 G가 생성한 데이터를 구별하는 경쟁 과정
➡️ 이러한 경쟁은 두 모델이 각자의 목적을 달성시키기 위해 스스로 개선하도록 만든다.

<br>

📌 GAN의 핵심 아이디어는 두 모델의 adversarial learning을 통해 진짜같은 가짜를 생성하는 능력을 키우는 것!

혼련하는 동안 G와 D가 균형을 잘 맞춰 학습되어야 한다는 단점이 있다.

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by SEOJIN-Lab** [comment]
잘 읽었습니다:>

**Comment by binable43** [comment]
GAN의 기본 구조에 대해 다시 한 번 짚고 갈 수 있었어요 :) 잘 읽었습니다 👍

**Comment by m0oon0** [comment]
GAN 리뷰 잘 읽었습니다 😊
