### ISSUE TITLE
Neural Architecture Search With Reinforcement Learning

### ISSUE THREAD

**Issue by m0oon0** [gdscewha-3rd/Study-PaperReview#19]
NAS : 좋은 neural network architecture를 찾아주는 Neural Architecture Search

- neural network 구조를 찾기 위해 RNN controller을 사용함
- controller는 filter, stride 등 네트워크의 구조를 생성하고, 이렇게 생성된 아키텍쳐에 대해 validation accuracy를 계산
- 이 정확도를 reward로 보고, 강화학습을 적용해 controller를 업데이트
- skip connection 등을 적용하기 위해, 각 layer에 anchor point를 두고, attention을 통해 이전 layer와 연결할지 말지를 계산함

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by SEOJIN-Lab** [comment]
처음 보는 개념이네요...! 좋은 정보 공유 감사합니다!

**Comment by binable43** [comment]
저도 이번에 처음 NAS에 대해 알게 되었는데 좀 더 찾아보니 종류가 아주 많네요! 덕분에 또 하나 알아갑니다 👍

**Comment by minha62** [comment]
NAS를 처음 들어봤는데 흥미롭네요! 좋은 내용 감사합니다:)
