### ISSUE TITLE
A Brief Introduction into Machine Learning

### ISSUE THREAD

**Issue by SEOJIN-Lab** [gdscewha-3rd/Study-PaperReview#2]
- 이 논문은 간단한 요약일뿐 모든 알고리즘을 소개하고 있지는 않다.
    
    → Supervised Classification 중 Classification Algorithms을 자세히 다루고 있음
    
    - **Traditional Techniques**
        - k-Nearest Neighbor Classification
        - Linear Discriminant Analysis
        - Decision Trees (figure 있음)
        - Neural Networks (figure 있음)
    - **Large Margin Algorithms**
        - Support Vector Machines (수식 있음)
        - Boosting

**Comment by binable43** [comment]
Large Margin Algorithm은 이번에 처음 들어본건데 찾아보니 너무 흥미롭네요!! 잘 읽고 갑니다 서진님 :)

**Comment by ssongedev** [comment]
잘 읽었습니다! ☺️

**Comment by chaerin314** [comment]
잘 읽었습니다:)

**Comment by minha62** [comment]
오 저도 이 논문 한번 봐야겠어요! 감사합니다:)

**Comment by m0oon0** [comment]
저도 large margin 알고리즘이라고 부르는지 처음 알았네요!! 잘 읽었습니다😃
