### ISSUE TITLE
Understanding LSTM -- a tutorial into Long Short-Term Memory Recurrent Neural Networks

### ISSUE THREAD

**Issue by ssongedev** [gdscewha-3rd/Study-PaperReview#20]
- RNN
  - time prediction tasks를 모델링 하기 위한 dynamic classifier
  - 한계점: Vanishing Error Problem (limited to look back in time for approximately ten timesteps)  
- LSTM
  - Vanishing Error Problem 해결
  - Memory block의 access control, forget gate -> 제한된 크기의 데이터가 오랜 시간 기억됨
  - 한계점: 네트워크 토폴리지 수정 필요

**Comment by SEOJIN-Lab** [comment]
잘 읽었습니다:>

**Comment by binable43** [comment]
잘 읽고 갑니다~ 👍

**Comment by minha62** [comment]
RNN의 한계점을 LSTM이 보완한 것이군요! 좋은 내용 감사합니다:)

**Comment by m0oon0** [comment]
잘 읽었습니다! 😊
