### ISSUE TITLE
Recognition of Multi Label Fashion Styles based on Transfer Learning and Graph Convolution Network

### ISSUE THREAD

**Issue by chaerin314** [gdscewha-3rd/Study-PaperReview#21]
- 학습 속도 및 정확도 향상을 위해 전이학습 기법 적용
- 레이블 사이의 연관성과 각 레이블의 의미를 추출하기 위해 GCN 적용
- gradient vanishing 문제를 해결하기 위해 ResNet 사용
![캡처](https://user-images.githubusercontent.com/95239486/168479360-c4141348-f855-4852-9e15-4d5cfe801820.PNG)

- 비교모델(기본적인 구조의 CNN 모델) 대비 모든 지표에서 성능 우수

**Comment by SEOJIN-Lab** [comment]
이번에 multi label classification을 할 일이 생겼는데 도움이 되는 논문이네요! 
좋은 논문 공유 감사합니다:>

**Comment by binable43** [comment]
모델 전반적인 구조가 아주 흥미롭네요! 덕분에 잘 읽고 갑니다 👍

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by minha62** [comment]
GCN에 대해서 더 찾아보고 싶어지네요! 좋은 내용 감사합니다:)

**Comment by m0oon0** [comment]
GCN이 이렇게 쓰이는군요!! 잘 읽었습니다😊
