### ISSUE TITLE
DP-CGAN: Differentially Private Synthetic Data and Label Generation

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#22]
## Preliminaries
- GAN : 원본 데이터를 기반으로 새로운 합성 데이터를 생성하는 Generator와 생성된 합성 데이터와 원본 데이터를 비교하며 구별하는 Discriminator가 서로 경쟁하면서 데이터를 생성하고 분류하는 모델
- CGAN(Conditional GAN) : Generator와 Discriminator가 추가 정보 y(class label, 다른 modality 등)를 가진 확장된 형태의 GAN 모델
- DP(Differential Privacy) : 민감 데이터를 학습한 Machine Learning 모델의 프라이버시를 보호하는 기술. 전체적인 데이터에 대해서는 파악하고 있지만 특정한 individual member에 대해서는 학습하면 안된다.

### How it works
1) discriminator network에서 real/fake data를 구별하여 loss의 gradient를 DP 방식으로 각각 training
2) clipping된 real/fake gradient의 합을 계산한 후 gaussian noise 추가
3) RDP(Rényi Differential Privacy) 기반의 privacy accountant에서 각 step별 소모된 privacy budget을 누적하여 update
4) generator network에서 non-private oprimizer로 training

### Result
- DP-CGAN의 AuROC는 CGAN with basic DP보다 높다
- DP-CGAN에서 새롭게 사용된 clipping, perturbing 기술이 성능을 향상시킴

**Comment by SEOJIN-Lab** [comment]
이름만 알고 있는 기술이었는데 이번 기회에 자세히 알게 됐네요!
좋은 논문 공유 감사합니다:>

**Comment by ssongedev** [comment]
잘 읽었습니다 :)

**Comment by minha62** [comment]
DP-CGAN을 GAN, CGAN, DP로 나눠서 설명해주셔서 이해가 잘 됐어요! 좋은 내용 감사합니다:)

**Comment by m0oon0** [comment]
흥미로운 내용이네요!! 잘 읽었습니다😊
