### ISSUE TITLE
You Only Look Once: Unified, Real-Time Object Detection

### ISSUE THREAD

**Issue by SEOJIN-Lab** [gdscewha-3rd/Study-PaperReview#23]
### Abstract

YOLO - object detection

- 하나의 신경망이 한 번의 계산으로 bounding box와 class probability 예측
    
    → regression으로 간주
    
- end-to-end
- 빠른 속도 (1초에 45개의 프레임을 처리)
    
    Fast YOLO는 1초당 155개의 프레임을 처리
    
- 좋은 성능
    
    다른 real-time detectors보다 mAP가 두 배

### Unified Detection

1. input image into an S × S grid
2. bounding box와 각 bounding box에 대한 신뢰도 점수를 예측
    
    평가 지표 = 
    
    ![Untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F35f20c0f-aae1-4386-aa6f-f079c60bdcc8%2FUntitled.png?table=block&id=5fe77620-6105-48a1-a8c5-076fd7694a13&spaceId=89244720-69b3-4c4a-834d-153c889ed6a9&width=2000&userId=bd1ae9b7-87a5-45b3-9084-89e5858443da&cache=v2)
    
3. Each grid cell also predicts C conditional class probabilities
4. Final detections
![](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd7d2e219-38d4-456d-9ca9-6a6174d28dcd%2FUntitled.png?table=block&id=dfaf7b08-d449-4fc8-becd-13abe891bfc5&spaceId=89244720-69b3-4c4a-834d-153c889ed6a9&width=2000&userId=bd1ae9b7-87a5-45b3-9084-89e5858443da&cache=v2)

### **Conclusion**

- YOLO는 단순하면서도 빠르고 정확
- 훈련 단계에서 보지 못한 새로운 이미지에 대해서도 객체를 잘 검출함

**Comment by minha62** [comment]
잘 읽었습니다:)

**Comment by ssongedev** [comment]
잘 읽었습니다! :)

**Comment by m0oon0** [comment]
잘 읽었습니다 👍
