### ISSUE TITLE
Text Detection and Recognition in the Wild: A Review

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#25]
Text recognition은 크게 두 가지 카테고리
1. 스캔된 인쇄 문서 내에 있는 text를 recognition
2. 일상 scene에서 캡처된 text를 recognition

흔히 쓰는 OCR은 해상도가 높은 인쇄 문서의 경우(1번 경우)엔 우수한 성능을 보이지만, 2번의 경우에서는 여러 challenge에 부딪혀 대부분의 경우에 실패
> 여기서 말하는 challenge는 `text의 다양성`, `scene의 복잡성`, `왜곡적 요인들`

<br>

Scene text detection / recognition의 challenge를 다루기 위해 제안된 다양한 기법들을 아래와 같이 두 가지로 분류
1. 고전적인 기계 학습 기반 접근

- scene 내 text를 detection/recognition할 때, 특징 추출 기법과 기계 학습 모델을 결합한 것에 기반
- 수평 방향의 text를 detection/recognition하는 경우 우수한 성능을 보였지만, 여러 방향성을 가지거나 곡선 형태인 text의 경우엔 실패

2. 딥러닝 기반 접근

- 다양한 상황에서 캡처된 text에 대해 딥러닝 기반 접근은 end-to-end 방식의 detection/recognition에서 효율적

**Comment by SEOJIN-Lab** [comment]
잘 읽었습니다:>

**Comment by ssongedev** [comment]
잘 읽었습니다! :)

**Comment by m0oon0** [comment]
현실적인 데이터에는 딥러닝이 효율적이군요!! 잘 읽었습니다👍
