### ISSUE TITLE
Seq2SQL : Generating structured queries from natural language using reinforcement learning

### ISSUE THREAD

**Issue by m0oon0** [gdscewha-3rd/Study-PaperReview#26]
Model > Seq2SQL : DNN for translating Natural Language Questions to SQL Queries
Dataset > WikiSQL : 80654 questions, SQL queries corpus from wikipedia.

1. aggregation operator classifier
Compute attention score over aggregation operations (COUNT, MIN, MAX, ...) for input tokens.

2. SELECT column pointer
Produce the representations for the columns using LSTM.
Compute attention score for each column and make a distribution over possible columns.
1,2 can be trained using cross entropy loss.

3. WHERE clause generator
Apply reinforcement learning  
Instead of teacher forcing at each step of query generation, sample from the output distribution to obtain the next token.  
Execute the generated SQL query against the database to obtain a reward. (compute by the result)

**Comment by minha62** [comment]
쿼리를 생성하는 자연어처리도 있군요! 흥미로운 주제네요! 좋은 내용 감사합니다:)

**Comment by SEOJIN-Lab** [comment]
SQL로 자연어 처리를 할 수 있다니...! 좋은 논문 공유 감사합니다:>

**Comment by ssongedev** [comment]
잘 읽었습니다! :)
