### ISSUE TITLE
Blockchain and Federated Learning for Privacy-Preserved Data Sharing in Industrial IoT

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#27]
### Consist of Two Modules
1) Permissioned blockchain module
•retrieval transactions
•Data sharing transactions
2) federated learning module
<img width="424" alt="fig3" src="https://user-images.githubusercontent.com/81629116/169732263-958c7890-1589-42ee-bcab-2c5323ccb5ef.png">
-> 각각의 IoT device들이 unstructured data들을 생성하고, 이 data들은 blockchain으로 전달. compute node들 중 정확도를 기준으로 leader를 뽑음. (Federated Learning이 적용)
 
<br>
<br>

### Data Sharing Process
1) Initialization
2) Registering Retrieval Records
3) Launching Data Sharing
4) Data Retrieval
5) Data Model Learning
6) Generating Data Sharing Records
7) Carrying Out Consensus

**Comment by minha62** [comment]
IoT와 블록체인과 federated learning이 융합되어 있는 게 흥미롭네요! 좋은 내용 감사합니다:)

**Comment by SEOJIN-Lab** [comment]
잘 읽었습니다 !!

**Comment by ssongedev** [comment]
잘 읽었습니다! :)

**Comment by m0oon0** [comment]
좋은 주제 잘 읽었습니다! 👍
