### ISSUE TITLE
Generative Models for Effective ML on Private, Decentralized Datasets

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#28]
## Intro
- train 정보가 민감 & 분산되어 있는 환경 → modeler how debugging?
- privacy-preserving generating model
    - inference or train 하는 동안 오류를 디버깅하는 과정에서 직접적인 data 검사를 대신한다
    - 검사할 수 없는 data 전체 또는 하위 집합을 대표하고 개인 정보를 보호할 수 있다

## Differentially Private Federated Generative Model
- 어떠한 특정 user의 data도 조사할 필요가 없다. 광범위하게 의미있는 데이터를 발견하는 것이 목표.
- 실제 사용자 데이터 대신 적절한 합성 예제 사용을 고려하는 것이 당연. 이를 위해 deep generative model을 기반

### Debugging During Training with RNNs
- DP Federated RNNs for Generating Natural Language Model

### Debugging During Training with GANs
- DP Federated GANs for Generating Image Data

## Reference
- [Google TechTalks](https://www.youtube.com/watch?v=DV5FUe5mlGk)

**Comment by ssongedev** [comment]
잘 읽었습니다! :)

**Comment by chaerin314** [comment]
Federated Learning을 공부하시나봐요! 흥미로운 내용 잘 읽었습니다:)

**Comment by minha62** [comment]
디버깅에 관련된 논문은 처음 보네요! 좋은 내용 감사합니다:)
