### ISSUE TITLE
Zero-Shot Learning Through Cross-Modal Transfer

### ISSUE THREAD

**Issue by ssongedev** [gdscewha-3rd/Study-PaperReview#29]
이 논문에서 제안하는 것: deep learned word와 image representation에 기반한 제로샷 러닝 (제로샷 러닝: 한 번도 본 적 없는 데이터를 분류 가능하도록 학습)
- seen class, unseen class로 분류
- 신경망 모델로 학습된 단어의 의미적 공간에 매핑
- 새로운 seen class에 해당하는지를 결정하는 novelty detection 이용
- key ideas
	- semantic word vector representation: 이미지와 텍스트 사이 지식 전달
	- bayesian framework: zero-shot과 seen class를 하나의 프레임 워크로 묶음

**Comment by binable43** [comment]
제로샷 러닝 들어보기만 했는데 시정님 덕분에 좋은 논문 알아갑니다~ 잘 읽었어요!

**Comment by chaerin314** [comment]
저도 제로샷 러닝 처음 들어보는데 신기하네요! 이상치 탐지를 이용하는군요.. 잘 읽었습니다!:)

**Comment by minha62** [comment]
저도 제로샷 러닝이 흥미롭네요!! 좋은 내용 감사합니다:)
