### ISSUE TITLE
Federated Learning: Strategies for Improving Communication Efficiency

### ISSUE THREAD

**Issue by binable43** [gdscewha-3rd/Study-PaperReview#3]
- FL의 목적 : 좋은 성능의 Centralized model 학습
- 학습 데이터 조건 : 불안정하고 상대적으로 느린 네트워크 연결을 가진 clients에 분포되어 있어야 함
- Client가 각 round마다 독립적으로 local data를 이용하여 현재 모델에 대한 update 계산하고 이를 central server에 전송. 모이게 된 Update들은 새로운 global model을 계산하기 위해 합해짐

- 본 논문에서는 Uplink communication costs를 줄이기 위한 두 가지 방법 제시
    1) **structured updates** : 적은 수의 변수를 사용하여 parameterized된 제한된 space로부터 직접 update 학습 ex) low-rank 혹은 random mask
    2) **sketched updates** : full model update 학습하여 서버 전송 전에 quantization, random rotations, subsampling 등의 기법들을 함께 사용해 압축

→ Convolutional, Recurrent networks에 대해 communication cost를 거의 100배 수준으로 감소

**Comment by ssongedev** [comment]
잘 읽었습니다! ☺️

**Comment by chaerin314** [comment]
communication costs를 고려하는 기계학습이군요! 알아두면 좋을 것 같네요. 잘 읽었습니다:)

**Comment by minha62** [comment]
100배 수준으로 감소라니!! Federated Learning 들어만 봤는데 은빈님 덕분에 어떤 건지 알게 되었네요! 감사합니다:)

**Comment by SEOJIN-Lab** [comment]
Federated Learning은 처음 들어봤네요...! 은빈님 덕분에 좋은 기술 알고 갑니다:>

**Comment by m0oon0** [comment]
분산학습같은거군요.!! 흥미로운 주제 잘 읽고 갑니다 😃
