### ISSUE TITLE
DETR: End-to-End Object Detection with Transformers

### ISSUE THREAD

**Issue by SEOJIN-Lab** [gdscewha-3rd/Study-PaperReview#30]
### **[Background]**

1개의 grid에 여러 object가 겹쳐있을 때

해당 grid에서 여러 object를 탐지하기 어려움 → `anchor` 제안

⇒ 미리 정해진 ratio의 anchor box만 생성이 가능

⇒ input image에 맞춰서 동적으로  bounding box를 생성하기 어려움

`NMS` : 최대값을 제외한 값들을 억제하는 알고리즘

→ 하나의 물체에 대해 여러개의 bounding box가 생기는 문제 방지

**<객체 탐지 문제의 목표>**

input image에서 찾을 수 있는 모든 객체들에 대한 class와 bounding box 정보를 얻는 것

**`DETR`**

**transformer의 encoder-decoder 구조와 bipartite matching**

⇒ set-based global loss

⇒ 학습된 object queries의 fixed small set만 주어지면, 
     object와 global image context 사이의 관계를 추론하고, 최종적인 예측 set을 곧바로 반환

<br>

### **[DETR architecture]**

![Untitled](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc0ec407f-edc4-4297-9d84-ff4ef622b8b0%2FUntitled.png?table=block&id=3406cc54-23bc-4c2a-bf9e-bf7774e055a5&spaceId=89244720-69b3-4c4a-834d-153c889ed6a9&width=2000&userId=bd1ae9b7-87a5-45b3-9084-89e5858443da&cache=v2)

- compact feature representation을 추출하는 **CNN backbone**
- encoder-decoder **transformer**
- 최종적인 detection 예측을 반환하는 simple **feed forward network** (FFN)

**Comment by binable43** [comment]
저한테 객체 탐지 기술은 완전 낯선 분야인데 DETR 기술은 너무 흥미롭네요! 덕분에 잘 읽고 갑니다 👍

**Comment by chaerin314** [comment]
저도 요즘 transformer를 공부하고 있는데 다양한 분야에서 사용되는 최신 기술인 것 같아요ㅎㅎ

**Comment by ssongedev** [comment]
잘 읽었습니다 :) 👍

**Comment by minha62** [comment]
transformer에 대한 논문이 자주 보이네요!!
좋은 내용 감사합니다:)
