### ISSUE TITLE
Deep Neural Networks for YouTube Recommendations

### ISSUE THREAD

**Issue by chaerin314** [gdscewha-3rd/Study-PaperReview#32]
- 특징
    1. deep **candidate generation** model 
    2. describe a separate deep **ranking** model
 
- 구조
![image](https://user-images.githubusercontent.com/95239486/170876151-6bbb95a6-eafb-4329-a32b-d2acc7a349ab.png)
    - Deep candidate generation model architecture
    ![image](https://user-images.githubusercontent.com/95239486/170876524-fa003ed4-0a30-422e-9f98-a6b55c6fce12.png)
    - Deep ranking network architecture
    ![image](https://user-images.githubusercontent.com/95239486/170876614-2d73c260-1b03-47cc-bf8c-52cbfbbdaaa8.png)

- 딥러닝을 이용하여 기존 추천 시스템에서 비약적인 발전을 이룸
    - withholding discrimative signals from the classifier -> 오버피팅 방지
    -  training example의 input에 나이 추가
    - watch time for positive examples & unity for negative examples -> expected watch time을 더 밀접하게 모델링(이전의  click-through rate보다 나아짐)

**Comment by binable43** [comment]
youtube 추천시스템이라니 너무 흥미로운 주제를 다룬 논문이네요!
좋은 내용 논문 감사합니다 👍

**Comment by ssongedev** [comment]
잘 읽었습니다 :) 👍

**Comment by minha62** [comment]
채린벗 저번에도 유튜브 추천 시스템에 대한 논문을 올리셨던 것 같은데 이쪽에 관심이 있나봐요! 
좋은 내용 감사합니다:)
