### ISSUE TITLE
EfficientDet: Scalable and Efficient Object Detection

### ISSUE THREAD

**Issue by SEOJIN-Lab** [gdscewha-3rd/Study-PaperReview#33]
# **EfficientDet: Scalable and Efficient Object Detection**

### Main Challenge

speed와 accuracy는 trade-off 관계

속도를 높이면서 정확도도 같이 높이는 모델 → 설계를 잘 해야 함

이런 모델을 설계하려면,

<br>

**Challenge 1**

**Efficient multi-scale feature fusion**

Feature Pyramid Network(FPN)

→ 서로 다른 input feature들을 합칠 때 구분없이 단순히 더하는 방식 ~ 이를 지적하고 있음

→ 해상도가 다름 ~ output feature에 기여하는 정도 또한 다름(주장)

     **weighted bi-directional FPN(BiFPN) 구조 제안**

<br>

**Challenge 2**

**Model scaling**

EfficientNet에서 제안한 Compound Scaling 기법

- 모델의 크기와 연산량를 결정하는 요소들을 동시에 고려하여 증가시키는 방법
    - input resolution
    - depth
    - width

→ 모든 곳에 적용 (backbone, feature network 등…)

### Main Contribution

- BiFPN을 제안
- Object Detection에 Compound Scaling을 적용하는 방법을 제안
- BiFPN과 Compound Scaling을 접목 →  EfficientDet 구조를 제안

### Figure

**[Weighted bidirectional feature network 구조]**

![image](https://user-images.githubusercontent.com/82519477/174423073-a4f0faee-5f2d-4283-94d8-c6b31100a616.png)

**[EfficientDet 구조]**

![image](https://user-images.githubusercontent.com/82519477/174423061-12f0cf40-304f-44ec-b4f0-93bda80f30b9.png)

<br>

**⇒ 정확도도 높고, 모델 크기도 작고, Latency도 낮아서 빠르게 동작**

### Conclusion

- 좋은 성능
- 효율성 아주 좋음 (+ Latency 관점에서도)

**Comment by m0oon0** [comment]
잘 읽었습니다!!

**Comment by minha62** [comment]
정리가 너무 깔끔해서 이해가 잘 됐어요! 좋은 내용 감사합니다:)
