### ISSUE TITLE
A Human-Following Mobile Robot Providing Natural and Universal Interfaces for Control With Wireless Electronic Devices

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#34]
논문에서 제안한 것
1. a human-following algorithm based on human path prediction 
2. a natural gesture interaction using RGB-D sensor

<br>

the human-following control system ➡ two feedback control loops
1) for linear motions
2) for rotational motions

To follow an operator effectively, a feedback control system is developed to maintain a certain distance between the operator and the robot and an anticipation for human-following.

<br>

![image](https://user-images.githubusercontent.com/71062967/174485579-c1dd0c96-5636-48f4-919d-195fb49bc1f9.png)

### Two operation modes

1. the human-tracking mode
-  laptop
   - process the position data from the Kinect sensor & RGB camera
   - calculate the distance and angular position error
   - plan robot's motion
   - send the commands to the robot to track the designated person
   
<br>

2. gesture-control mode
- laptop
   - process the positional data of joints of the person being tracked by the Kinect sensor
   - send pulse width modulation signals to the Arduino board of the lamps through the XBee modules
   
- Arduino board
   - process these signals(pulse width modulation signals) to turn the lamp ON/OFF

**Comment by SEOJIN-Lab** [comment]
흥미로운 내용 잘 읽었습니다 :>

**Comment by m0oon0** [comment]
잘 읽었습니다!!
