### ISSUE TITLE
What Happens To BERT Embeddings During Fine-tuning?

### ISSUE THREAD

**Issue by m0oon0** [gdscewha-3rd/Study-PaperReview#35]
![image](https://user-images.githubusercontent.com/79262676/174486895-a242fa9a-066b-41c4-a99c-69d197ef28fe.png)

Test (Freeze layers)
- Freezing first 8 layers of 12 BERT layers doesn't drop performance.
- Later layers are task-specific, therefore tuned during fine-tuning by downstream task data . Early layers remain almost stable.

Results
- We can save resources by freezing the early layers instead of tuning the entire network.
- Best result when using last 4 layers as features. (concatenate)
- The final layer might be too specific to pretrained task (language modeling) ; To apply to general tasks, we need more overall information.

**Comment by SEOJIN-Lab** [comment]
잘 읽었습니다!

**Comment by minha62** [comment]
좋은 내용 감사합니다:)
