### ISSUE TITLE
YOLOv4: Optimal Speed and Accuracy of Object Detection

### ISSUE THREAD

**Issue by ssongedev** [gdscewha-3rd/Study-PaperReview#4]
- YOLOv4
  - a CNN-based object detector
  - a state-of-the-art detector (speed & accuracy)
  - it is trained and operates in a real-time on a conventional GPU
  - Architecture
    - Backbone: CSPDarknet53
    - Neck: SPP block, PANet
    - Head: YOLOv3 (anchor based)
- Verification of the influence of BoF and BoS during training
  - Bag of freebies(BoF): the methods that only change the training strategy or only increase the training cost
  - Bag of specials(BoS): plugin modules and post-processing methods that only increase the inference cost by a small amount but can significantly improve the accuracy of object detection

- Additional improvement for training on single GPU
  - Mosaic data augmentation
  - Self-Adversarial Training(SAT)
  - Cross mini-Batch Normalization(CmBN)
  - modified SAM, modified PAN

**Comment by binable43** [comment]
architecture가 backbone, neck, head로 나뉜다는 걸 처음 알게 되었는데 너무 흥미롭네요! 그리고 하나의 GPU만으로도 SOTA를 찍었다니 대단하네요. 시정님 덕분에 잘 읽고 갑니다 :)

**Comment by chaerin314** [comment]
Object detection도 흥미롭네요ㅎㅎ 잘 읽었습니다:)

**Comment by minha62** [comment]
하나의 GPU에서 augmentation을 할 때 mosaic가 좋군요..!! 좋은 내용 감사합니다:)

**Comment by SEOJIN-Lab** [comment]
저번 프로젝트 할 때 yolov4 사용에 엄청 진을 뺐는데 좋은 정보를 담고 있네요! 잘 읽었습니다:>

**Comment by m0oon0** [comment]
객체인식은 성능을 높이려는 시도들이 다양하고 아이디어가 많은 것 같아요! 잘 읽었습니다😃
