### ISSUE TITLE
A Novel Dynamic Hand Gesture and Movement Trajectory Recognition model for Non-Touch HRI Interface

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#40]
### divide system into two parts
1. Hand State and Gesture Recognition
    - the method detects and identifies the skeleton, the hand area and fingertips that expresses the hand states (open/closed), and different motion functions using hand gestures
2. Action identification System
    - describes the way to get instruction, modification of size and location, and explains how to perform the gestural action without touching any device

<br>

![image](https://user-images.githubusercontent.com/71062967/175818702-ef2fb673-c90e-4799-a5ff-93c23aee11fc.png)

<br>

### 1. Skeleton information using kinect sensor
The location of the both hands can be determined from the skeleton information which is correlative with the shoulders and head of the user.

![image](https://user-images.githubusercontent.com/71062967/175818896-9d77a60f-5fdc-4aa7-be20-486580339b7b.png)

<br>

### 2. Dynamic hand state & gesture recognition
dynamic hand gesture recognition ⇒ challenging
: If a person continuously waves his hand in front of Kinect device like following figure and machine can understand the direction one by one at a certain time

![image](https://user-images.githubusercontent.com/71062967/175818891-49d3e833-b8fa-4648-bf8a-24b3aa7e639d.png)

<br>

### 3. Hand area and movement detection

After confirming the size and location of the user, he/she can perform the Motion-Functions.
=> To perform those functions, the distance between different positions of the skeleton are measured using the Euclidean distance by Equation.

![image](https://user-images.githubusercontent.com/71062967/175818921-5a021076-20d5-4cb6-b973-91b9feb5a42b.png)

**Comment by SEOJIN-Lab** [comment]
>
