### ISSUE TITLE
Easy Data Augmentation Techniques for Boosting Performance on Text Classification Tasks

### ISSUE THREAD

**Issue by m0oon0** [gdscewha-3rd/Study-PaperReview#5]
• 데이터 변형, 노이즈 추가 등의 방법을 통해 데이터를 증강할 수 있음이 알려진 이미지, 오디오 등의 데이터와 달리, NLP 분야에서는 이러한 방법을 통해 데이터를 생성하기가 어려움
• 기존 연구 : Back translation, Language model을 통한 생성 및 교체
But 성능 대비 cost가 높아 잘 사용되지 않음

• 4가지 방법을 제안
[예시 문장] A sad, superior human comedy played out on the back roads of life.
1. Synonym Replacement
A lamentable, superior human comedy played out on the backward road of life. 
2. Random Insertion
A sad, superior human comedy played out on funniness the back roads of life.
3. Random Swap
A sad, superior human comedy played out on roads back the of life. 
4. Random Deletion
A sad, superior human out on the roads of life.
		
• 긴 문장은 짧은 문장에 비해 noise/변형의 영향을 덜 받음
-> 변형되는 단어의 개수가 문장의 길이에 비례하도록 (n=αl)
• 단어 및 문장을 변형하는 것이 class label에 영향을 주지 않음을 확인하기 위해서 RNN을 거쳐 latent space를 추출하고
t-SNE를 적용한 결과, 증강된 데이터도 원본 데이터의 label 분포를 벗어나지 않음
• α (변형 비율)이 클수록 성능이 오히려 떨어지는데, Random Insertion에서는 α값이 커질수록 성능이 안정적으로 오름, 
α = 0.1일 때 대체로 성능이 가장 좋음
• 데이터셋의 크기에 따른 optimal 증강 비율 추천

**Comment by ssongedev** [comment]
잘 읽었습니다! ☺️

**Comment by chaerin314** [comment]
저도 NLP에 관심이 있었는데, 저렇게 변형된 data도 class label에 영향을 주지 않는다니 신기하네요!! 잘 읽었습니다:)

**Comment by minha62** [comment]
NLP를 공부한 적이 없는데도 정리가 깔끔해서 이해가 잘 됐어요! 감사합니다:)

**Comment by SEOJIN-Lab** [comment]
NLP에도 Data Augmentation이 있다니...! 흥미로운 내용 잘 읽었습니다:>

**Comment by binable43** [comment]
오 예전에 NLP 프로젝트 진행한 적 있었는데 증강하는 방법에 대해 잘 배워갑니다! 감사합니다 :)
