### ISSUE TITLE
The YouTube Video Recommendation System_1

### ISSUE THREAD

**Issue by chaerin314** [gdscewha-3rd/Study-PaperReview#6]
유튜브 추천 시스템 디자인
- Goals : 정기적인 update, top-N 추천, explicit control 제공
- Challenges: 영상에 대한 metadata가 적을 경우, 영상의 길이도 짧고 비교적 쉽게 시청 가능, 바이럴 등
- Recent, fresh, diverse, relevant to the user's recent actions. / understood and debugging in isolation.
- Input : 
    1.  content data
    2. user activity data
- Related videos 계산 방법 : r(v_i,v_j) = c_ij / f(v_i,v_j)
    i.e., Relatedness score = co-visitation count / normalizing function(global popularity)
- Seed set "S" := Union of {favorited, liked, rated, added to playlists}
- 추천영상 후보군 정하는 방법 : 
    - Seed set S와 related된 video set : C_1(S) = (Union of v_i in S) R_i => narrow recommendation
    - S의 모든 v로부터 거리 n인 video set : C_n(S) = (Union of v_i in C_{n-1}) R_i 
    - C_final = (Union of C_i) \ S
- Ranking 하는 방법 : 다음 3가지의 선형결합
    1. video quality
    2. user specificity
    3. diversification
- Evaluation : Unpersonalized recommendation system보다 207% click rate가 향상됨

**Comment by ssongedev** [comment]
잘 읽었습니다! ☺️

**Comment by minha62** [comment]
흥미로운 주제네요! 잘 읽었습니다:)

**Comment by SEOJIN-Lab** [comment]
전에 일했던 회사에서 유튜브 SEO 리서치를 했었는데,
시스템 디자인을 읽어보니 유튜브 추천 시스템이 더 와닿는 거 같네요! 좋은 정보 감사합니다:>

**Comment by binable43** [comment]
평소에 유튜브 추천 시스템에 잘 생각해보지 않았는데 덕분에 잘 읽고 갑니다 :)

**Comment by m0oon0** [comment]
비디오 후보군 랭킹을 그렇게 하는군요!! 잘 읽었습니다😃
