### ISSUE TITLE
You Only Look Once: Unified, Real-Time Object Detection

### ISSUE THREAD

**Issue by minha62** [gdscewha-3rd/Study-PaperReview#7]
### Prior work (ex. DPM, R-CNN)
- repurpose classifiers to perform detection
- use a  sliding window approach (DPM) or region proposal methods (R-CNN)

After classification, post-processing is used in order to
1. refine the bounding boxes
2. eliminate duplicate detections
3. rescore the boxes based on other objects in the scene

🤔 complex pipelines!! ➡️ slow & hard to optimize

---
### YOLO

- reframe object detection as a single regression problem
- unified architecture
- simple pipeline ➡️ can be optimized end-to-end directly on detection performance

👍 extremely fast
👍 reasons globally about the image -> FP on background⬇️
👍 learns generalizable representations of objects

**Comment by ssongedev** [comment]
잘 읽었습니다! ☺️

**Comment by chaerin314** [comment]
YOLO가 생각보다 비교적 최근에 나온 기술이었네요! 잘 읽었습니다:)

**Comment by SEOJIN-Lab** [comment]
yolo 최고...! 잘 읽었습니다:>

**Comment by binable43** [comment]
YOLO가 빠르긴 빠르군요!!! 덕분에 잘 읽고 갑니다 👍

**Comment by m0oon0** [comment]
역시 이름에 걸맞는 모델이네요ㅎㅎ 잘 읽었습니다!
