### ISSUE TITLE
MediaPipe: A Framework for Building Perception Pipelines

### ISSUE THREAD

**Issue by ssongedev** [gdscewha-3rd/Study-PaperReview#9]
MediaPipe: Perception(ML)을 위한 파이프라인 구축을 위한 프레임워크
- 파이프라인: **모듈식 방향 그래프**
  - 구성 요소(calculator)는 같은 인터페이스를 공유: **calculator 재사용 가능**
    -> 다양한 하드웨어 플랫폼에서 동일한 동작으로 실행 가능
    -> 개발자가 파이프라인을 점진적으로 프로토타이핑 가능
- Architecture
  - **Calculators**: inference 및 processing을 하는 구성요소, 재사용 가능, 병렬 실행 시 한 calculator 당 최대 한 스레드에서 실행
  - Packets: 데이터 기본 단위, timestamps + a shared pointer, immutable
  - Streams, Graph, Side packets, GraphConfig
- 시계열 처리를 위한 Implementation
  - Scheduling
    1. Scheduling logic
       - calculator 내부에서 데이터 처리
       - 각 그래프에 적어도 하나의 scheduler queue, 한 queue 당 한 executor
    2. Synchronization primitives
       - 분산처리 (서로 다른 calculators가 다른 timestamp의 Packets 동시에 처리)
       - timestamp의 입력 동기화 중요
    3. Input policies
    4. Flow control
  - GPU 지원: Opaque buffer type, OpenGL 지원   
- 성능 분석 Tools: Tracer, Visualizer
- 적용 예시: Object detection, Face landmark detection and segmentation

**Comment by binable43** [comment]
궁금해서 더 찾아보니 간편하게 응용 프로그램을 개발할 수 있는 프레임워크군요! 나중에 한번 써보고 싶어요 :) 잘 읽고 갑니다!!

**Comment by SEOJIN-Lab** [comment]
헉 이번에 우연히 mediapipe를 다른 곳에서 쓸 예정인데 너무 도움되는 논문이네요! 정리 감사합니다:>

**Comment by chaerin314** [comment]
pipeline을 위한 프레임워크군요..! 처음 들어봤는데 흥미롭게 잘 읽었습니다:)

**Comment by minha62** [comment]
활용할 수 있는 곳이 많을 것 같아요! 좋은 내용 감사합니다:)
